name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: print goodbye
        run: echo "bye"
    
